FROM node:8

WORKDIR /usr/src/babysteps
COPY babysteps/babysteps.js ./
COPY babysteps/package*.json ./
RUN npm install

WORKDIR /usr/src/app

COPY stepOne/package*.json ./

RUN npm install

COPY stepOne/act1worker.js .

CMD [ "npm", "start" ]
